server:
  port: 8081
  servlet:
    context-path: /mybatisDemo


#数据库的连接信息：5项，这里我是mysql8的连接信息
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatisTest?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver