server:
  port: 8088
  servlet:
    context-path: /mybatisDemo1


#数据库的连接信息：5项，这里我是mysql8的连接信息
spring:
  datasource:
    url: jdbc:mysql://1.116.215.137:3306/mybatisTest?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    password: lihm.29588
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: mybatisSpringBootDemo
      maximum-pool-size: 15
      minimum-idle: 10
      connection-timeout: 60000
      idle-timeout: 60000

      
mybatis:
  type-aliases-package: com.guihua.mybatis_springboot.web.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
